### ISSUE TITLE
Key presses are ignored in main menu

### ISSUE THREAD

**Issue by trufanov-nok** [DJs3000/DeltaShadow#3]
Have successfully built DS on Linux. Launched it. And couldn't go further than Main Menu bcs only cursor keys of my kayboard are wortking in the game. I mean I can select menu items, but can't enter inside them.   
I've debugged a bit and found out that SDL_PollEvent() returns a russian key syms for WASDM whatever I do. I tried to switch kayboard locale with hotkeys, launch the app with different locales by default, launch the app with LC_ALL environment variable overriden.   
The keypess for Space key returns a right key code. And space is working to skip the intro. But isn't working for menu selection. I guess its processing is broken.  
And F1 key functionality isn't ported yet.  

I googled a bit and it seems that SDL12 is having issues with keyboard layout detection on Linux platforms. And SDL2 works fine.
So, 
> Заменить SdlDotNet и SDL на SDL2, или всё перевести на SDL.

I guess would be better to port everything to SDL2.

**Comment by DJs3000** [comment]
Hello. Try to confirm the action with the "N" or "B" key. Perhaps there will be SDL2 in the future.

**Comment by trufanov-nok** [comment]
They return `SdlDotNetCompat::Input::World52 (212)` and `SdlDotNetCompat::Input::World41 (201)` instead of `SdlDotNetCompat::Input::SDLK_n` and `SdlDotNetCompat::Input::SDLK_b` no matter what.

**Comment by DJs3000** [comment]
Я думаю можно и так писать. SdlDotNet работает поверх первого SDL и это наследие C# т.к. оригинальный код игры был написан на C#. В идеале нужно конечно избавиться от SdlDotNet совсем, но моих знаний C++ на это не хватает, может кто поможет решить это задачку. Я проверял на Разных линуксах и проблем с управлением не было, странно что у вас с этим проблемы.

**Comment by trufanov-nok** [comment]
Думаю, проще разом выкинуть и SdlDotNet и SDL, и переписать все на SDL2 и Qt.

**Comment by DJs3000** [comment]
Согласен, единственно не вижу смысла тянуть туда Qt.

**Comment by trufanov-nok** [comment]
Ну, там GUI по F1 показывать надо, плюс многие вещи в Qt делаются проще, чем в c++
